# Generated by Django 6.0.7 on 2026-07-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ai_recommendations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='antivirus_status',
            field=models.CharField(blank=True, default='Active & Updated', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='battery_health_pct',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='disk_health_pct',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='encryption_status',
            field=models.CharField(blank=True, default='BitLocker Enabled', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='health_score',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='asset',
            name='hostname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='mac_address',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='os_name',
            field=models.CharField(blank=True, default='Windows 11 Pro', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='qr_code_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='risk_score',
            field=models.IntegerField(default=1),
        ),
    ]
