# Generated by Django 6.0.7 on 2026-07-27 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clearance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancerequest',
            name='certificate_hash',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='certificate_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='cleared_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='finance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_approved_as_finance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='ict_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_verified_as_ict', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clearancerequest',
            name='manager_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clearances_approved_as_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
